### ISSUE TITLE
Feature Request: Support Keyboard Function Key Settings

### ISSUE THREAD

**Issue by bgszsk** [KAMIKAZEUA/NativeDisplayBrightness#1]
Brilliant (pun intended) app! 

**Request:** Accommodate the user's system setting for function keys behavior.

**Background:** macOS allows users to enable use of F1, F2, etc. keys as standard function keys. When this setting is selected, only when pressing the Fn with a function key are the special features, like brightness adjustment, triggered. When this setting is checked, I expect to have F1, F2 as standard function keys, with the brightness adjusted only when I press Fn + F1. 

**Case:** In Adobe apps, F1 typically loads application Help. F2 is a hotkey. These are not easily remapped. Pressing F2 in Lightroom adjusts the screen brightness, which is not the expected behavior.

**Comment by Anywhere-Music-Player** [comment]
This is like well know request :) 
But original app(my fork only adds GUI and color management with some little improvements)
 https://www.tonymacx86.com/threads/beta-release-nativedisplaybrightness-0-0-5-testing-updated.205564/ 

> TIP: If you're using an original Apple keyboard, this app won't work with your F1 F2 keys straight away. 
> You can use Function+F1 / Function+F2.
> To map Function+F1/2 to just F1/2, there are several options:
> You can flip Function+F1/2 behavior with FunctionFlip as discussed on the second page of this thread
> You can apply a Clover patch that will remap the brightness keys to F1/F2

Also, it's probably Karabiner can solve this( this I just found so far) https://github.com/tekezo/Karabiner-Elements/issues/497 maybe this issue fixed. 

p.s. I don't have Apple keyboard and it's cost too much for me. I can't buy it and so I can't try to solve this problem...

**Comment by filliph** [comment]
> p.s. I don't have Apple keyboard and it's cost too much for me. I can't buy it and so I can't try to solve this problem...

You can buy a second hand wired Apple keyboard for next to nothing on eBay :)

I bought my 2nd gen Wired Apple Keyboard for about £25 (not sure where you're from so I can't do the currency conversion, sorry!)

**Comment by Anywhere-Music-Player** [comment]
This should work https://www.tonymacx86.com/threads/beta-release-nativedisplaybrightness-0-0-5-testing-updated.205564/page-5#post-1453641 or you can try to find any other solution on macOS forum. I don't think that it can be done in other way, like by fixing app code.
