### ISSUE TITLE
REQ: Support for El Capitan

### ISSUE THREAD

**Issue by patrickrushton** [KAMIKAZEUA/NativeDisplayBrightness#2]

**Comment by Anywhere-Music-Player** [comment]
Can't be implemented, because I don't have it. Just use latest macOS, whats the problem?

**Comment by patrickrushton** [comment]
Mac Pro 2008 - the latest macOS is not supported unfortunately.

**Comment by Anywhere-Music-Player** [comment]
I'm using macOS High Sierra 10.13.3 on my hardware:

- Intel Core i3-4330 3.5GHz
- Gigabyte GA-H87M-D3H
- Kingston SSD 120Gb
- Kingston DDR3-1600 8192MB

So, I can't downgrade and try to fix some crash on old version of macOS.
