### ISSUE TITLE
Support for contrast adjustment

### ISSUE THREAD

**Issue by jans-y** [KAMIKAZEUA/NativeDisplayBrightness#6]
Hello,

This project is absolutely amazing. I have been looking for something like this for a long time.

I would like to ask you for a possibility to control the contrast as well (at least at the dock) because some monitors are still too bright in a not so well-lit room. Lowering the Contrast for example from 75% to 50% can reduce the eye fatigue significantly.

Thank you for your hard work.

**Comment by Anywhere-Music-Player** [comment]
For this you have Color Temperature, set it accordingly. Only current implementation of real monitor brightness will be in this app.

**Comment by jans-y** [comment]
Thank you.

I already use the NightShift (Color Temperature).

Some displays like Lenovo with lower quality panels unfortunately still need adjustments to the contrast to have the overall amount of light bearable in the lower lit room.

I respect your choice and despite of that I would like to send you a small donation for your hard work.

Thanks.

**Comment by Anywhere-Music-Player** [comment]
It's free app and I will never take any donations.
